#############################################################################
# Makefile for building: OpenPST
# Generated by qmake (3.0) (Qt 5.4.2)
# Project:  OpenPST.pro
# Template: app
# Command: /usr/lib64/qt5/bin/qmake-qt5 -spec linux-g++ CONFIG+=debug -o Makefile OpenPST.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Ilib/serial/include -Isrc -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib64/qt5/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = OpenPST1.0.0
DISTDIR = /run/media/raab/Storage/Projects/cross-platform/openpst/openpst/.tmp/OpenPST1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = lib/serial/src/serial.cc \
		src/util/hexdump.cpp \
		src/util/endian.cpp \
		src/util/sleep.cpp \
		src/qc/hdlc.cpp \
		src/qc/crc.cpp \
		src/main.cpp \
		src/gui/main_window.cpp \
		src/gui/mbn_tool_window.cpp \
		src/gui/sahara_window.cpp \
		src/gui/streaming_dload_window.cpp \
		src/gui/send_raw_window.cpp \
		src/serial/sahara_serial.cpp \
		src/serial/hdlc_serial.cpp \
		src/serial/streaming_dload_serial.cpp \
		src/gui/qcdm_window.cpp \
		src/serial/qcdm_serial.cpp \
		src/worker/sahara_memory_read_worker.cpp \
		src/worker/sahara_image_transfer_worker.cpp \
		lib/serial/src/impl/unix.cc \
		lib/serial/src/impl/list_ports/list_ports_linux.cc moc_main_window.cpp \
		moc_qcdm_window.cpp \
		moc_mbn_tool_window.cpp \
		moc_sahara_window.cpp \
		moc_streaming_dload_window.cpp \
		moc_send_raw_window.cpp \
		moc_sahara_memory_read_worker.cpp \
		moc_sahara_image_transfer_worker.cpp
OBJECTS       = serial.o \
		hexdump.o \
		endian.o \
		sleep.o \
		hdlc.o \
		crc.o \
		main.o \
		main_window.o \
		mbn_tool_window.o \
		sahara_window.o \
		streaming_dload_window.o \
		send_raw_window.o \
		sahara_serial.o \
		hdlc_serial.o \
		streaming_dload_serial.o \
		qcdm_window.o \
		qcdm_serial.o \
		sahara_memory_read_worker.o \
		sahara_image_transfer_worker.o \
		unix.o \
		list_ports_linux.o \
		moc_main_window.o \
		moc_qcdm_window.o \
		moc_mbn_tool_window.o \
		moc_sahara_window.o \
		moc_streaming_dload_window.o \
		moc_send_raw_window.o \
		moc_sahara_memory_read_worker.o \
		moc_sahara_image_transfer_worker.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/c++11.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		OpenPST.pro lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/include/definitions.h \
		src/qc/mbn.h \
		src/qc/diag.h \
		src/qc/diag_nv.h \
		src/qc/dload.h \
		src/qc/sahara.h \
		src/qc/streaming_dload.h \
		src/qc/crc.h \
		src/qc/hdlc.h \
		src/util/hexdump.h \
		src/util/endian.h \
		src/util/sleep.h \
		src/gui/main_window.h \
		src/gui/qcdm_window.h \
		src/gui/mbn_tool_window.h \
		src/gui/sahara_window.h \
		src/gui/streaming_dload_window.h \
		src/gui/send_raw_window.h \
		src/serial/sahara_serial.h \
		src/serial/streaming_dload_serial.h \
		src/serial/hdlc_serial.h \
		src/serial/qcdm_serial.h \
		src/worker/sahara_memory_read_worker.h \
		src/worker/sahara_image_transfer_worker.h \
		lib/serial/include/serial/impl/unix.h lib/serial/src/serial.cc \
		src/util/hexdump.cpp \
		src/util/endian.cpp \
		src/util/sleep.cpp \
		src/qc/hdlc.cpp \
		src/qc/crc.cpp \
		src/main.cpp \
		src/gui/main_window.cpp \
		src/gui/mbn_tool_window.cpp \
		src/gui/sahara_window.cpp \
		src/gui/streaming_dload_window.cpp \
		src/gui/send_raw_window.cpp \
		src/serial/sahara_serial.cpp \
		src/serial/hdlc_serial.cpp \
		src/serial/streaming_dload_serial.cpp \
		src/gui/qcdm_window.cpp \
		src/serial/qcdm_serial.cpp \
		src/worker/sahara_memory_read_worker.cpp \
		src/worker/sahara_image_transfer_worker.cpp \
		lib/serial/src/impl/unix.cc \
		lib/serial/src/impl/list_ports/list_ports_linux.cc
QMAKE_TARGET  = OpenPST
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = OpenPST


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_main_window.h ui_mbn_tool_window.h ui_sahara_window.h ui_send_raw_window.h ui_streaming_dload_window.h ui_qcdm_window.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OpenPST.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/c++11.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		OpenPST.pro \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile OpenPST.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/shell-unix.conf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/c++11.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
OpenPST.pro:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile OpenPST.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents lib/serial/include/serial/serial.h lib/serial/include/serial/v8stdint.h src/include/definitions.h src/qc/mbn.h src/qc/diag.h src/qc/diag_nv.h src/qc/dload.h src/qc/sahara.h src/qc/streaming_dload.h src/qc/crc.h src/qc/hdlc.h src/util/hexdump.h src/util/endian.h src/util/sleep.h src/gui/main_window.h src/gui/qcdm_window.h src/gui/mbn_tool_window.h src/gui/sahara_window.h src/gui/streaming_dload_window.h src/gui/send_raw_window.h src/serial/sahara_serial.h src/serial/streaming_dload_serial.h src/serial/hdlc_serial.h src/serial/qcdm_serial.h src/worker/sahara_memory_read_worker.h src/worker/sahara_image_transfer_worker.h lib/serial/include/serial/impl/unix.h $(DISTDIR)/
	$(COPY_FILE) --parents lib/serial/src/serial.cc src/util/hexdump.cpp src/util/endian.cpp src/util/sleep.cpp src/qc/hdlc.cpp src/qc/crc.cpp src/main.cpp src/gui/main_window.cpp src/gui/mbn_tool_window.cpp src/gui/sahara_window.cpp src/gui/streaming_dload_window.cpp src/gui/send_raw_window.cpp src/serial/sahara_serial.cpp src/serial/hdlc_serial.cpp src/serial/streaming_dload_serial.cpp src/gui/qcdm_window.cpp src/serial/qcdm_serial.cpp src/worker/sahara_memory_read_worker.cpp src/worker/sahara_image_transfer_worker.cpp lib/serial/src/impl/unix.cc lib/serial/src/impl/list_ports/list_ports_linux.cc $(DISTDIR)/
	$(COPY_FILE) --parents resources/ui/main_window.ui resources/ui/mbn_tool_window.ui resources/ui/sahara_window.ui resources/ui/send_raw_window.ui resources/ui/streaming_dload_window.ui resources/ui/qcdm_window.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_main_window.cpp moc_qcdm_window.cpp moc_mbn_tool_window.cpp moc_sahara_window.cpp moc_streaming_dload_window.cpp moc_send_raw_window.cpp moc_sahara_memory_read_worker.cpp moc_sahara_image_transfer_worker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main_window.cpp moc_qcdm_window.cpp moc_mbn_tool_window.cpp moc_sahara_window.cpp moc_streaming_dload_window.cpp moc_send_raw_window.cpp moc_sahara_memory_read_worker.cpp moc_sahara_image_transfer_worker.cpp
moc_main_window.cpp: ui_main_window.h \
		src/gui/sahara_window.h \
		ui_sahara_window.h \
		src/serial/sahara_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/sahara.h \
		src/qc/mbn.h \
		src/util/hexdump.h \
		src/util/sleep.h \
		src/qc/streaming_dload.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/endian.h \
		src/worker/sahara_memory_read_worker.h \
		src/worker/sahara_image_transfer_worker.h \
		src/gui/send_raw_window.h \
		ui_send_raw_window.h \
		src/gui/mbn_tool_window.h \
		ui_mbn_tool_window.h \
		src/gui/qcdm_window.h \
		ui_qcdm_window.h \
		src/qc/diag_nv.h \
		src/serial/qcdm_serial.h \
		src/serial/hdlc_serial.h \
		src/qc/diag.h \
		src/gui/streaming_dload_window.h \
		ui_streaming_dload_window.h \
		src/serial/streaming_dload_serial.h \
		src/gui/main_window.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/lib/serial/include -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/5.1.1 -I/usr/include/c++/5.1.1/x86_64-redhat-linux -I/usr/include/c++/5.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I/usr/local/include -I/usr/include src/gui/main_window.h -o moc_main_window.cpp

moc_qcdm_window.cpp: ui_qcdm_window.h \
		src/qc/diag_nv.h \
		src/serial/qcdm_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/serial/hdlc_serial.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/hexdump.h \
		src/qc/diag.h \
		src/gui/qcdm_window.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/lib/serial/include -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/5.1.1 -I/usr/include/c++/5.1.1/x86_64-redhat-linux -I/usr/include/c++/5.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I/usr/local/include -I/usr/include src/gui/qcdm_window.h -o moc_qcdm_window.cpp

moc_mbn_tool_window.cpp: ui_mbn_tool_window.h \
		src/qc/mbn.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		src/util/hexdump.h \
		src/util/endian.h \
		src/gui/mbn_tool_window.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/lib/serial/include -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/5.1.1 -I/usr/include/c++/5.1.1/x86_64-redhat-linux -I/usr/include/c++/5.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I/usr/local/include -I/usr/include src/gui/mbn_tool_window.h -o moc_mbn_tool_window.cpp

moc_sahara_window.cpp: ui_sahara_window.h \
		src/serial/sahara_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/sahara.h \
		src/qc/mbn.h \
		src/util/hexdump.h \
		src/util/sleep.h \
		src/qc/streaming_dload.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/endian.h \
		src/worker/sahara_memory_read_worker.h \
		src/worker/sahara_image_transfer_worker.h \
		src/gui/sahara_window.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/lib/serial/include -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/5.1.1 -I/usr/include/c++/5.1.1/x86_64-redhat-linux -I/usr/include/c++/5.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I/usr/local/include -I/usr/include src/gui/sahara_window.h -o moc_sahara_window.cpp

moc_streaming_dload_window.cpp: ui_streaming_dload_window.h \
		src/qc/streaming_dload.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		src/serial/streaming_dload_serial.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/serial/hdlc_serial.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/hexdump.h \
		src/util/endian.h \
		src/gui/streaming_dload_window.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/lib/serial/include -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/5.1.1 -I/usr/include/c++/5.1.1/x86_64-redhat-linux -I/usr/include/c++/5.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I/usr/local/include -I/usr/include src/gui/streaming_dload_window.h -o moc_streaming_dload_window.cpp

moc_send_raw_window.cpp: ui_send_raw_window.h \
		src/gui/send_raw_window.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/lib/serial/include -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/5.1.1 -I/usr/include/c++/5.1.1/x86_64-redhat-linux -I/usr/include/c++/5.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I/usr/local/include -I/usr/include src/gui/send_raw_window.h -o moc_send_raw_window.cpp

moc_sahara_memory_read_worker.cpp: src/serial/sahara_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/sahara.h \
		src/qc/mbn.h \
		src/util/hexdump.h \
		src/util/sleep.h \
		src/worker/sahara_memory_read_worker.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/lib/serial/include -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/5.1.1 -I/usr/include/c++/5.1.1/x86_64-redhat-linux -I/usr/include/c++/5.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I/usr/local/include -I/usr/include src/worker/sahara_memory_read_worker.h -o moc_sahara_memory_read_worker.cpp

moc_sahara_image_transfer_worker.cpp: src/serial/sahara_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/sahara.h \
		src/qc/mbn.h \
		src/util/hexdump.h \
		src/util/sleep.h \
		src/worker/sahara_image_transfer_worker.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/lib/serial/include -I/run/media/raab/Storage/Projects/cross-platform/openpst/openpst/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/5.1.1 -I/usr/include/c++/5.1.1/x86_64-redhat-linux -I/usr/include/c++/5.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I/usr/local/include -I/usr/include src/worker/sahara_image_transfer_worker.h -o moc_sahara_image_transfer_worker.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_main_window.h ui_mbn_tool_window.h ui_sahara_window.h ui_send_raw_window.h ui_streaming_dload_window.h ui_qcdm_window.h
compiler_uic_clean:
	-$(DEL_FILE) ui_main_window.h ui_mbn_tool_window.h ui_sahara_window.h ui_send_raw_window.h ui_streaming_dload_window.h ui_qcdm_window.h
ui_main_window.h: resources/ui/main_window.ui
	/usr/lib64/qt5/bin/uic resources/ui/main_window.ui -o ui_main_window.h

ui_mbn_tool_window.h: resources/ui/mbn_tool_window.ui
	/usr/lib64/qt5/bin/uic resources/ui/mbn_tool_window.ui -o ui_mbn_tool_window.h

ui_sahara_window.h: resources/ui/sahara_window.ui
	/usr/lib64/qt5/bin/uic resources/ui/sahara_window.ui -o ui_sahara_window.h

ui_send_raw_window.h: resources/ui/send_raw_window.ui
	/usr/lib64/qt5/bin/uic resources/ui/send_raw_window.ui -o ui_send_raw_window.h

ui_streaming_dload_window.h: resources/ui/streaming_dload_window.ui
	/usr/lib64/qt5/bin/uic resources/ui/streaming_dload_window.ui -o ui_streaming_dload_window.h

ui_qcdm_window.h: resources/ui/qcdm_window.ui
	/usr/lib64/qt5/bin/uic resources/ui/qcdm_window.ui -o ui_qcdm_window.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

serial.o: lib/serial/src/serial.cc lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		lib/serial/include/serial/impl/win.h \
		lib/serial/include/serial/impl/unix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serial.o lib/serial/src/serial.cc

hexdump.o: src/util/hexdump.cpp src/util/hexdump.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hexdump.o src/util/hexdump.cpp

endian.o: src/util/endian.cpp src/util/endian.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o endian.o src/util/endian.cpp

sleep.o: src/util/sleep.cpp src/util/sleep.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sleep.o src/util/sleep.cpp

hdlc.o: src/qc/hdlc.cpp src/qc/hdlc.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		src/qc/crc.h \
		src/util/hexdump.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hdlc.o src/qc/hdlc.cpp

crc.o: src/qc/crc.cpp src/qc/crc.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crc.o src/qc/crc.cpp

main.o: src/main.cpp src/gui/main_window.h \
		ui_main_window.h \
		src/gui/sahara_window.h \
		ui_sahara_window.h \
		src/serial/sahara_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/sahara.h \
		src/qc/mbn.h \
		src/util/hexdump.h \
		src/util/sleep.h \
		src/qc/streaming_dload.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/endian.h \
		src/worker/sahara_memory_read_worker.h \
		src/worker/sahara_image_transfer_worker.h \
		src/gui/send_raw_window.h \
		ui_send_raw_window.h \
		src/gui/mbn_tool_window.h \
		ui_mbn_tool_window.h \
		src/gui/qcdm_window.h \
		ui_qcdm_window.h \
		src/qc/diag_nv.h \
		src/serial/qcdm_serial.h \
		src/serial/hdlc_serial.h \
		src/qc/diag.h \
		src/gui/streaming_dload_window.h \
		ui_streaming_dload_window.h \
		src/serial/streaming_dload_serial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

main_window.o: src/gui/main_window.cpp src/gui/main_window.h \
		ui_main_window.h \
		src/gui/sahara_window.h \
		ui_sahara_window.h \
		src/serial/sahara_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/sahara.h \
		src/qc/mbn.h \
		src/util/hexdump.h \
		src/util/sleep.h \
		src/qc/streaming_dload.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/endian.h \
		src/worker/sahara_memory_read_worker.h \
		src/worker/sahara_image_transfer_worker.h \
		src/gui/send_raw_window.h \
		ui_send_raw_window.h \
		src/gui/mbn_tool_window.h \
		ui_mbn_tool_window.h \
		src/gui/qcdm_window.h \
		ui_qcdm_window.h \
		src/qc/diag_nv.h \
		src/serial/qcdm_serial.h \
		src/serial/hdlc_serial.h \
		src/qc/diag.h \
		src/gui/streaming_dload_window.h \
		ui_streaming_dload_window.h \
		src/serial/streaming_dload_serial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_window.o src/gui/main_window.cpp

mbn_tool_window.o: src/gui/mbn_tool_window.cpp src/gui/mbn_tool_window.h \
		ui_mbn_tool_window.h \
		src/qc/mbn.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		src/util/hexdump.h \
		src/util/endian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mbn_tool_window.o src/gui/mbn_tool_window.cpp

sahara_window.o: src/gui/sahara_window.cpp src/gui/sahara_window.h \
		ui_sahara_window.h \
		src/serial/sahara_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/sahara.h \
		src/qc/mbn.h \
		src/util/hexdump.h \
		src/util/sleep.h \
		src/qc/streaming_dload.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/endian.h \
		src/worker/sahara_memory_read_worker.h \
		src/worker/sahara_image_transfer_worker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sahara_window.o src/gui/sahara_window.cpp

streaming_dload_window.o: src/gui/streaming_dload_window.cpp src/gui/streaming_dload_window.h \
		ui_streaming_dload_window.h \
		src/qc/streaming_dload.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		src/serial/streaming_dload_serial.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/serial/hdlc_serial.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/hexdump.h \
		src/util/endian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o streaming_dload_window.o src/gui/streaming_dload_window.cpp

send_raw_window.o: src/gui/send_raw_window.cpp src/gui/send_raw_window.h \
		ui_send_raw_window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o send_raw_window.o src/gui/send_raw_window.cpp

sahara_serial.o: src/serial/sahara_serial.cpp src/serial/sahara_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/sahara.h \
		src/qc/mbn.h \
		src/util/hexdump.h \
		src/util/sleep.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sahara_serial.o src/serial/sahara_serial.cpp

hdlc_serial.o: src/serial/hdlc_serial.cpp src/serial/hdlc_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/hexdump.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hdlc_serial.o src/serial/hdlc_serial.cpp

streaming_dload_serial.o: src/serial/streaming_dload_serial.cpp src/serial/streaming_dload_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/serial/hdlc_serial.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/hexdump.h \
		src/qc/streaming_dload.h \
		src/util/endian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o streaming_dload_serial.o src/serial/streaming_dload_serial.cpp

qcdm_window.o: src/gui/qcdm_window.cpp src/gui/qcdm_window.h \
		ui_qcdm_window.h \
		src/qc/diag_nv.h \
		src/serial/qcdm_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/serial/hdlc_serial.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/hexdump.h \
		src/qc/diag.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcdm_window.o src/gui/qcdm_window.cpp

qcdm_serial.o: src/serial/qcdm_serial.cpp src/serial/qcdm_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/serial/hdlc_serial.h \
		src/qc/hdlc.h \
		src/qc/crc.h \
		src/util/hexdump.h \
		src/qc/diag.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcdm_serial.o src/serial/qcdm_serial.cpp

sahara_memory_read_worker.o: src/worker/sahara_memory_read_worker.cpp src/worker/sahara_memory_read_worker.h \
		src/serial/sahara_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/sahara.h \
		src/qc/mbn.h \
		src/util/hexdump.h \
		src/util/sleep.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sahara_memory_read_worker.o src/worker/sahara_memory_read_worker.cpp

sahara_image_transfer_worker.o: src/worker/sahara_image_transfer_worker.cpp src/worker/sahara_image_transfer_worker.h \
		src/serial/sahara_serial.h \
		src/include/definitions.h \
		src/include/win_stdint.h \
		src/include/win_inttypes.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h \
		src/qc/sahara.h \
		src/qc/mbn.h \
		src/util/hexdump.h \
		src/util/sleep.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sahara_image_transfer_worker.o src/worker/sahara_image_transfer_worker.cpp

unix.o: lib/serial/src/impl/unix.cc lib/serial/include/serial/impl/unix.h \
		lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix.o lib/serial/src/impl/unix.cc

list_ports_linux.o: lib/serial/src/impl/list_ports/list_ports_linux.cc lib/serial/include/serial/serial.h \
		lib/serial/include/serial/v8stdint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o list_ports_linux.o lib/serial/src/impl/list_ports/list_ports_linux.cc

moc_main_window.o: moc_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_window.o moc_main_window.cpp

moc_qcdm_window.o: moc_qcdm_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcdm_window.o moc_qcdm_window.cpp

moc_mbn_tool_window.o: moc_mbn_tool_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mbn_tool_window.o moc_mbn_tool_window.cpp

moc_sahara_window.o: moc_sahara_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sahara_window.o moc_sahara_window.cpp

moc_streaming_dload_window.o: moc_streaming_dload_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_streaming_dload_window.o moc_streaming_dload_window.cpp

moc_send_raw_window.o: moc_send_raw_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_send_raw_window.o moc_send_raw_window.cpp

moc_sahara_memory_read_worker.o: moc_sahara_memory_read_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sahara_memory_read_worker.o moc_sahara_memory_read_worker.cpp

moc_sahara_image_transfer_worker.o: moc_sahara_image_transfer_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sahara_image_transfer_worker.o moc_sahara_image_transfer_worker.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

